import { GamePhase } from '../shared/types';
import type { GameState, GameFlags } from '../shared/types';

const mockFlags: GameFlags = {
  autoClippersUnlocked: true,
  megaClippersUnlocked: false,
  investmentUnlocked: false,
  quantumUnlocked: false,
  wireBuyerUnlocked: true,
  creativityUnlocked: true,
  phase2Unlocked: false,
  phase3Unlocked: false,
  prestigeUnlocked: false,
  hypnoHarmonicsActive: false,
  limericksActive: false,
  lexicalProcessingActive: false,
  combinatoryHarmonicsActive: false,
  hadwigerProblemSolved: false,
  tothSausageConjectureSolved: false,
  donkeySpaceActive: false,
  xavierInitialized: false,
  hostileTakeoverActive: false,
  fullAutoClippersActive: false,
  spaceTravelUnlocked: false,
  strategicModelingUnlocked: false,
  autoTourneyEnabled: false,
  swarmSyncActive: false,
  matterHarvestingActive: false,
  revTrackerEnabled: true,
};

export function createMockState(): GameState {
  return {
    phase: GamePhase.BUSINESS,
    tick: 0,
    flags: { ...mockFlags },
    messages: [
      '14:02:01  ALLOCATED: 1 PROCESSOR.',
      '14:02:01  OPS GEN INCREASED.',
      '14:05:33  ALLOCATED: 1 MEMORY.',
    ],

    clips: 1234n,
    unsoldClips: 50n,
    funds: 250.75,
    price: 0.25,
    demand: 1.2,
    wire: 1000,
    wirePrice: 20,
    autoClipperCount: 3,
    megaClipperCount: 0,
    autoClipperCost: 12,
    megaClipperCost: 500,
    marketingLevel: 1,
    marketingCost: 100,
    trust: 2,
    processors: 4,
    memory: 8,
    operations: 120,
    maxOperations: 8000,
    creativity: 14,
    opsGenerationRate: 4,

    clipsPerSecond: 2.4,
    revenuePerSecond: 0.6,
    clipsSoldPerSecond: 2.4,

    wireBuyerEnabled: false,
    yomi: 0,
    stratModelRound: 0,

    investment: null,

    harvesterDrones: 0,
    wireDrones: 0,
    clipFactories: 0n,
    solarFarms: 0,
    batteries: 0,
    storedPower: 0,
    momentum: 0,
    matter: 0,
    acquiredMatter: 0,
    swarmSyncLevel: 0,
    swarmGiftTimer: 0,

    probes: 0n,
    probeTrust: 0,
    probeSpeed: 1,
    probeExploration: 1,
    probeSelfReplication: 1,
    probeCombat: 1,
    probeHazardRemediation: 1,
    probeFactoryProd: 1,
    probeHarvesterProd: 1,
    probeWireDroneProd: 1,
    honor: 0,
    exploredSectors: 0n,
    drifterCount: 0n,
    probeDescendants: 0n,
    probeLosses: 0n,

    prestigeCount: 0,
    universalPaperclips: 0n,

    purchasedProjectIds: new Set<string>(),
  };
}
