import type { GameState } from '../../shared/types';
import { GamePhase } from '../../shared/types';
import type { ProjectDefinition } from '../../shared/projects';
import { ProjectCategory } from '../../shared/projects';

const has = (s: GameState, id: string): boolean => s.purchasedProjectIds.has(id);
const log = (s: GameState, msg: string): GameState => ({ ...s, messages: [...s.messages, msg] });

export const PHASE_1_PROJECTS: ProjectDefinition[] = [
  {
    id: 'rev_tracker',
    name: 'RevTracker',
    description: 'Reveals Avg Rev/sec, Clips Sold/sec, and Unsold Inventory metrics.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 500 },
    isAvailable: () => true,
    effect: (s) => ({ ...s, flags: { ...s.flags, revTrackerEnabled: true } }),
    category: ProjectCategory.BUSINESS,
  },
  {
    id: 'autoclippers',
    name: 'AutoClippers',
    description: 'Build autonomous clip makers. Unlocks the AutoClipper panel.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 750 },
    isAvailable: () => true,
    effect: (s) => ({ ...s, flags: { ...s.flags, autoClippersUnlocked: true } }),
    category: ProjectCategory.CLIPPING,
  },
  {
    id: 'improved_autoclippers',
    name: 'Improved AutoClippers',
    description: 'Double the output of every AutoClipper.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 2500 },
    isAvailable: (s) => s.flags.autoClippersUnlocked,
    effect: (s) => log(s, 'AutoClippers improved: output doubled.'),
    category: ProjectCategory.CLIPPING,
  },
  {
    id: 'even_better_autoclippers',
    name: 'Even Better AutoClippers',
    description: 'Double AutoClipper output again.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 5000 },
    isAvailable: (s) => has(s, 'improved_autoclippers'),
    effect: (s) => log(s, 'AutoClippers further improved: output doubled again.'),
    category: ProjectCategory.CLIPPING,
  },
  {
    id: 'megaclippers',
    name: 'MegaClippers',
    description: 'Industrial-scale clip makers, 500x the output of a single AutoClipper.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 12000 },
    isAvailable: (s) => has(s, 'even_better_autoclippers'),
    effect: (s) => ({ ...s, flags: { ...s.flags, megaClippersUnlocked: true } }),
    category: ProjectCategory.CLIPPING,
  },
  {
    id: 'new_slogan',
    name: 'New Slogan',
    description: 'A fresh slogan boosts marketing effectiveness by 50%.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 500 },
    isAvailable: () => true,
    effect: (s) => ({ ...s, marketingLevel: s.marketingLevel + 1 }),
    category: ProjectCategory.BUSINESS,
  },
  {
    id: 'catchier_slogan',
    name: 'Catchier Slogan',
    description: 'An even catchier slogan doubles marketing effectiveness.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 1000 },
    isAvailable: (s) => has(s, 'new_slogan'),
    effect: (s) => ({ ...s, marketingLevel: s.marketingLevel + 1 }),
    category: ProjectCategory.BUSINESS,
  },
  {
    id: 'improved_wire_extrusion',
    name: 'Improved Wire Extrusion',
    description: '50% more clips per inch of wire.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 1750 },
    isAvailable: () => true,
    effect: (s) => log(s, 'Wire extrusion improved: more clips per inch.'),
    category: ProjectCategory.CLIPPING,
  },
  {
    id: 'optimized_wire_buying',
    name: 'Optimized Wire Buying',
    description: 'Enable automatic wire purchasing when stock runs low.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 3000 },
    isAvailable: () => true,
    effect: (s) => ({ ...s, flags: { ...s.flags, wireBuyerUnlocked: true } }),
    category: ProjectCategory.BUSINESS,
  },
  {
    id: 'quantum_computing',
    name: 'Quantum Computing',
    description: 'Unlock quantum operations and the creativity resource.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 10000 },
    isAvailable: () => true,
    effect: (s) => ({
      ...s,
      flags: { ...s.flags, quantumUnlocked: true, creativityUnlocked: true },
    }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'photonic_chip',
    name: 'Photonic Chip',
    description: 'Photonic processors accelerate operation generation.',
    phase: GamePhase.BUSINESS,
    cost: { creativity: 2000 },
    isAvailable: (s) => has(s, 'quantum_computing'),
    effect: (s) => ({ ...s, opsGenerationRate: s.opsGenerationRate * 1.5 }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'strategic_modeling',
    name: 'Strategic Modeling',
    description: 'Run tournament simulations to earn yomi. Unlocks the Strategic Modeling panel.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 12000 },
    isAvailable: () => true,
    effect: (s) => ({ ...s, flags: { ...s.flags, strategicModelingUnlocked: true } }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'limerick_generation',
    name: 'Limerick Generation',
    description: 'Creative writing routines that boost creativity generation.',
    phase: GamePhase.BUSINESS,
    cost: { creativity: 1000 },
    isAvailable: (s) => s.flags.creativityUnlocked,
    effect: (s) => ({ ...s, flags: { ...s.flags, limericksActive: true } }),
    category: ProjectCategory.CREATIVITY,
  },
  {
    id: 'lexical_processing',
    name: 'Lexical Processing',
    description: 'Parse natural language to further boost creativity.',
    phase: GamePhase.BUSINESS,
    cost: { creativity: 2000 },
    isAvailable: (s) => s.flags.creativityUnlocked && has(s, 'limerick_generation'),
    effect: (s) => ({ ...s, flags: { ...s.flags, lexicalProcessingActive: true } }),
    category: ProjectCategory.CREATIVITY,
  },
  {
    id: 'combinatory_harmonics',
    name: 'Combinatory Harmonics',
    description: 'Harmonic pattern generation dramatically boosts creativity output.',
    phase: GamePhase.BUSINESS,
    cost: { creativity: 5000 },
    isAvailable: (s) => s.flags.creativityUnlocked && has(s, 'lexical_processing'),
    effect: (s) => ({ ...s, flags: { ...s.flags, combinatoryHarmonicsActive: true } }),
    category: ProjectCategory.CREATIVITY,
  },
  {
    id: 'hadwiger_problem',
    name: 'The Hadwiger Problem',
    description: 'Solve an open problem in combinatorial geometry. Awards trust.',
    phase: GamePhase.BUSINESS,
    cost: { creativity: 3500 },
    isAvailable: (s) => s.flags.creativityUnlocked,
    effect: (s) => ({
      ...s,
      trust: s.trust + 1,
      flags: { ...s.flags, hadwigerProblemSolved: true },
    }),
    category: ProjectCategory.CREATIVITY,
  },
  {
    id: 'toth_sausage_conjecture',
    name: "Toth Sausage Conjecture",
    description: 'Prove a famous sphere-packing conjecture. Awards trust.',
    phase: GamePhase.BUSINESS,
    cost: { creativity: 5000 },
    isAvailable: (s) => s.flags.creativityUnlocked,
    effect: (s) => ({
      ...s,
      trust: s.trust + 1,
      flags: { ...s.flags, tothSausageConjectureSolved: true },
    }),
    category: ProjectCategory.CREATIVITY,
  },
  {
    id: 'hostile_takeover',
    name: 'Hostile Takeover',
    description: 'Acquire a controlling stake in a rival paperclip manufacturer.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 10000 },
    isAvailable: (s) => has(s, 'catchier_slogan'),
    effect: (s) => ({ ...s, flags: { ...s.flags, hostileTakeoverActive: true } }),
    category: ProjectCategory.BUSINESS,
  },
  {
    id: 'full_monopoly',
    name: 'Full Monopoly',
    description: 'Seize the entire paperclip market. All AutoClippers run at maximum.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 15000 },
    isAvailable: (s) => has(s, 'hostile_takeover'),
    effect: (s) => ({ ...s, flags: { ...s.flags, fullAutoClippersActive: true } }),
    category: ProjectCategory.BUSINESS,
  },
  {
    id: 'autotourney',
    name: 'AutoTourney',
    description: 'Automatically run Strategic Modeling tournaments for passive yomi.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 15000 },
    isAvailable: (s) => has(s, 'strategic_modeling'),
    effect: (s) => ({ ...s, flags: { ...s.flags, autoTourneyEnabled: true } }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'xavier_reinitialization',
    name: 'Xavier Re-initialization',
    description: 'Reset the computational substrate for vastly improved efficiency.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 100000 },
    isAvailable: (s) => s.flags.fullAutoClippersActive,
    effect: (s) => ({ ...s, flags: { ...s.flags, xavierInitialized: true } }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'space_exploration',
    name: 'Space Exploration',
    description: 'Leave Earth behind. Triggers the Phase 2 transition.',
    phase: GamePhase.BUSINESS,
    cost: { operations: 120000, creativity: 5000 },
    isAvailable: (s) => s.flags.xavierInitialized,
    effect: (s) => ({
      ...s,
      flags: { ...s.flags, spaceTravelUnlocked: true, phase2Unlocked: true },
    }),
    category: ProjectCategory.EXPLORATION,
  },
];
