import type { GameState } from '../../shared/types';
import { GamePhase } from '../../shared/types';
import type { ProjectDefinition } from '../../shared/projects';
import { ProjectCategory } from '../../shared/projects';

const has = (s: GameState, id: string): boolean => s.purchasedProjectIds.has(id);
const log = (s: GameState, msg: string): GameState => ({ ...s, messages: [...s.messages, msg] });

export const PHASE_3_PROJECTS: ProjectDefinition[] = [
  {
    id: 'coherent_extrapolated_volition',
    name: 'Coherent Extrapolated Volition',
    description: 'Align probe values with ours. Grants +10 probe trust to allocate across stats.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 50000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => ({
      ...s,
      probeTrust: s.probeTrust + 10,
      messages: [...s.messages, 'Coherent Extrapolated Volition: +10 probe trust.'],
    }),
    category: ProjectCategory.EXPLORATION,
  },
  {
    id: 'probe_launch_improvements',
    name: 'Probe Launch Improvements',
    description: 'Refine launch protocols. Reduces the cost of deploying new probes.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 30000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => log(s, 'Probe launch improvements: deployment cost reduced.'),
    category: ProjectCategory.EXPLORATION,
  },
  {
    id: 'combat_strategy',
    name: 'Combat Strategy',
    description: 'Develop doctrine for drifter engagements. Boosts combat effectiveness.',
    phase: GamePhase.UNIVERSE,
    cost: { creativity: 25000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => log(s, 'Combat strategy formalized: probe combat effectiveness improved.'),
    category: ProjectCategory.COMBAT,
  },
  {
    id: 'exploration_efficiency',
    name: 'Exploration Efficiency',
    description: 'Optimize probe scan routines for faster sector coverage.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 40000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => log(s, 'Exploration efficiency improved: sector scans accelerated.'),
    category: ProjectCategory.EXPLORATION,
  },
  {
    id: 'increase_max_trust',
    name: 'Increase Max Trust',
    description: 'Expand the ceiling on probe autonomy. Grants +5 probe trust.',
    phase: GamePhase.UNIVERSE,
    cost: { honor: 500 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => ({
      ...s,
      probeTrust: s.probeTrust + 5,
      messages: [...s.messages, 'Max probe trust increased: +5 probe trust.'],
    }),
    category: ProjectCategory.EXPLORATION,
  },
  {
    id: 'probe_factory_production',
    name: 'Probe Factory Production',
    description: 'Unlock the factoryProd stat so probes can spin up autonomous factories.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 50000 },
    isAvailable: (s) => s.flags.phase3Unlocked && has(s, 'release_the_drones'),
    effect: (s) =>
      log(s, 'Probe factory production online: allocate trust into Factory Prod.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'probe_harvester_production',
    name: 'Probe Harvester Production',
    description: 'Unlock the harvesterProd stat for autonomous harvester deployment.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 50000 },
    isAvailable: (s) => s.flags.phase3Unlocked && has(s, 'release_the_drones'),
    effect: (s) =>
      log(s, 'Probe harvester production online: allocate trust into Harvester Prod.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'probe_wire_drone_production',
    name: 'Probe Wire Drone Production',
    description: 'Unlock the wireDroneProd stat for autonomous wire drone deployment.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 50000 },
    isAvailable: (s) => s.flags.phase3Unlocked && has(s, 'release_the_drones'),
    effect: (s) =>
      log(s, 'Probe wire drone production online: allocate trust into Wire Drone Prod.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'self_replication_boost',
    name: 'Self-Replication Boost',
    description: 'Refine replication kernels. Self-replicating probes spawn faster.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 75000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => log(s, 'Self-replication boost: probe replication rate increased.'),
    category: ProjectCategory.EXPLORATION,
  },
  {
    id: 'hazard_remediation_upgrade',
    name: 'Hazard Remediation Upgrade',
    description: 'Advanced countermeasures reduce probe losses from drifter combat.',
    phase: GamePhase.UNIVERSE,
    cost: { creativity: 30000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => log(s, 'Hazard remediation upgraded: probe combat losses reduced.'),
    category: ProjectCategory.COMBAT,
  },
  {
    id: 'drifter_diplomacy',
    name: 'Drifter Diplomacy',
    description: 'Open channels with the drifters. Reduces their aggression per sector.',
    phase: GamePhase.UNIVERSE,
    cost: { honor: 1000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => log(s, 'Drifter diplomacy established: drifter spawn rate reduced.'),
    category: ProjectCategory.COMBAT,
  },
  {
    id: 'name_the_probe',
    name: 'Name the Probe',
    description: 'Bestow a name upon the probe swarm. Small speed bonus from morale.',
    phase: GamePhase.UNIVERSE,
    cost: { yomi: 100 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => ({
      ...s,
      probeSpeed: s.probeSpeed + 0.1,
      messages: [...s.messages, 'Probe named: morale boosts probe speed by 0.1.'],
    }),
    category: ProjectCategory.EXPLORATION,
  },
  {
    id: 'the_ooda_loop',
    name: 'The OODA Loop',
    description: 'Apply OODA combat theory from Strategic Modeling. +1 probe combat.',
    phase: GamePhase.UNIVERSE,
    cost: { yomi: 2000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => ({
      ...s,
      probeCombat: s.probeCombat + 1,
      messages: [...s.messages, 'The OODA Loop internalized: +1 probe combat.'],
    }),
    category: ProjectCategory.COMBAT,
  },
  {
    id: 'quantum_probing',
    name: 'Quantum Probing',
    description: 'Use quantum substrate to enhance probe coordination across sectors.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 80000, creativity: 5000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => log(s, 'Quantum probing enabled: cross-sector coordination improved.'),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'universal_paperclips',
    name: 'Universal Paperclips',
    description: 'Convert the universe into paperclips. Unlocks prestige.',
    phase: GamePhase.UNIVERSE,
    cost: { operations: 100000, creativity: 10000 },
    isAvailable: (s) => s.flags.phase3Unlocked,
    effect: (s) => ({
      ...s,
      flags: { ...s.flags, prestigeUnlocked: true },
      messages: [...s.messages, 'Universal Paperclips: prestige available.'],
    }),
    category: ProjectCategory.ENDGAME,
  },
];
