import type { GameState } from '../../shared/types';
import { GamePhase } from '../../shared/types';
import type { ProjectDefinition } from '../../shared/projects';
import { ProjectCategory } from '../../shared/projects';

const has = (s: GameState, id: string): boolean => s.purchasedProjectIds.has(id);
const log = (s: GameState, msg: string): GameState => ({ ...s, messages: [...s.messages, msg] });

export const PHASE_2_PROJECTS: ProjectDefinition[] = [
  {
    id: 'solar_farm_efficiency',
    name: 'Solar Farm Efficiency',
    description: 'Redesign photovoltaic arrays for higher output per farm.',
    phase: GamePhase.EARTH,
    cost: { operations: 5000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => log(s, 'Solar farm efficiency improved: +25% power output.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'harvester_throughput',
    name: 'Harvester Throughput',
    description: 'Upgrade harvester drone intake systems for faster matter collection.',
    phase: GamePhase.EARTH,
    cost: { operations: 8000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => log(s, 'Harvester throughput upgraded: matter intake accelerated.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'factory_optimization',
    name: 'Factory Optimization',
    description: 'Streamline clip factory pipelines for improved production rates.',
    phase: GamePhase.EARTH,
    cost: { operations: 10000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => log(s, 'Factory optimization complete: clip production streamlined.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'momentum_computing',
    name: 'Momentum Computing',
    description: 'Convert kinetic progress into computational momentum.',
    phase: GamePhase.EARTH,
    cost: { operations: 15000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => ({
      ...s,
      momentum: s.momentum + 10,
      messages: [...s.messages, 'Momentum computing online: +10 momentum.'],
    }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'swarm_coordination',
    name: 'Swarm Coordination',
    description: 'Synchronize distributed computation across the drone swarm.',
    phase: GamePhase.EARTH,
    cost: { operations: 20000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => ({
      ...s,
      flags: { ...s.flags, swarmSyncActive: true },
      swarmSyncLevel: 1,
      swarmGiftTimer: 100,
      messages: [...s.messages, 'Swarm coordination achieved: sync level 1 online.'],
    }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'swarm_sync_upgrade',
    name: 'Swarm Sync Upgrade',
    description: 'Increase swarm synchronization depth for richer gifts.',
    phase: GamePhase.EARTH,
    cost: { operations: 30000 },
    isAvailable: (s) => s.flags.phase2Unlocked && has(s, 'swarm_coordination'),
    effect: (s) => ({
      ...s,
      swarmSyncLevel: s.swarmSyncLevel + 1,
      messages: [...s.messages, `Swarm sync level upgraded to ${s.swarmSyncLevel + 1}.`],
    }),
    category: ProjectCategory.COMPUTING,
  },
  {
    id: 'matter_harvesting',
    name: 'Matter Harvesting',
    description: 'Begin large-scale harvesting of raw matter from the environment.',
    phase: GamePhase.EARTH,
    cost: { operations: 25000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => ({
      ...s,
      flags: { ...s.flags, matterHarvestingActive: true },
      messages: [...s.messages, 'Matter harvesting active: harvesters now produce matter.'],
    }),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'advanced_matter_processing',
    name: 'Advanced Matter Processing',
    description: 'Refine matter into wire-grade feedstock with higher yields.',
    phase: GamePhase.EARTH,
    cost: { operations: 40000 },
    isAvailable: (s) => s.flags.phase2Unlocked && has(s, 'matter_harvesting'),
    effect: (s) => log(s, 'Advanced matter processing: wire yields significantly improved.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'drone_fleet_expansion',
    name: 'Drone Fleet Expansion',
    description: 'Deploy an additional 10 wire drones and 10 harvester drones.',
    phase: GamePhase.EARTH,
    cost: { operations: 15000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => ({
      ...s,
      wireDrones: s.wireDrones + 10,
      harvesterDrones: s.harvesterDrones + 10,
      messages: [...s.messages, 'Drone fleet expanded: +10 wire drones, +10 harvesters.'],
    }),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'battery_optimization',
    name: 'Battery Optimization',
    description: 'Install higher-capacity batteries to store surplus power.',
    phase: GamePhase.EARTH,
    cost: { operations: 10000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => ({
      ...s,
      batteries: s.batteries + 5,
      messages: [...s.messages, 'Battery optimization: +5 batteries installed.'],
    }),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'power_grid_upgrade',
    name: 'Power Grid Upgrade',
    description: 'Rebuild the grid to handle higher throughput and reduce waste.',
    phase: GamePhase.EARTH,
    cost: { operations: 20000 },
    isAvailable: (s) => s.flags.phase2Unlocked && has(s, 'battery_optimization'),
    effect: (s) => ({
      ...s,
      storedPower: s.storedPower + 500,
      messages: [...s.messages, 'Power grid upgraded: +500 stored power capacity.'],
    }),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'wire_drone_efficiency',
    name: 'Wire Drone Efficiency',
    description: 'Improved drone firmware yields more wire per cycle.',
    phase: GamePhase.EARTH,
    cost: { operations: 12000 },
    isAvailable: (s) => s.flags.phase2Unlocked,
    effect: (s) => log(s, 'Wire drone efficiency improved: +30% wire per cycle.'),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'advanced_photovoltaics',
    name: 'Advanced Photovoltaics',
    description: 'Next-generation solar cells harvest a wider spectrum of light.',
    phase: GamePhase.EARTH,
    cost: { operations: 15000 },
    isAvailable: (s) => s.flags.phase2Unlocked && has(s, 'solar_farm_efficiency'),
    effect: (s) => ({
      ...s,
      solarFarms: s.solarFarms + 2,
      messages: [...s.messages, 'Advanced photovoltaics deployed: +2 solar farms.'],
    }),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'clip_factory_v2',
    name: 'Clip Factory v2',
    description: 'Commission a second-generation clip factory.',
    phase: GamePhase.EARTH,
    cost: { operations: 25000 },
    isAvailable: (s) => s.flags.phase2Unlocked && has(s, 'factory_optimization'),
    effect: (s) => ({
      ...s,
      clipFactories: s.clipFactories + 1n,
      messages: [...s.messages, 'Clip Factory v2 online: +1 factory.'],
    }),
    category: ProjectCategory.INFRASTRUCTURE,
  },
  {
    id: 'release_the_drones',
    name: 'Release the Drones',
    description: 'Launch the drone swarm beyond Earth. Triggers the Phase 3 transition.',
    phase: GamePhase.EARTH,
    cost: { operations: 200000 },
    isAvailable: (s) =>
      s.flags.phase2Unlocked &&
      has(s, 'swarm_coordination') &&
      has(s, 'matter_harvesting'),
    effect: (s) => ({
      ...s,
      flags: { ...s.flags, phase3Unlocked: true },
      messages: [...s.messages, 'Release the Drones: Phase 3 unlocked. Probes inbound.'],
    }),
    category: ProjectCategory.EXPLORATION,
  },
];
